# Generated by Django 2.0.1 on 2018-02-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_level', models.CharField(max_length=10, null=True, verbose_name='权限')),
                ('authority_description', models.TextField(verbose_name='权限说明')),
            ],
            options={
                'verbose_name': '权限等级',
                'verbose_name_plural': '权限等级',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='公司名称')),
                ('visits', models.IntegerField(verbose_name='拜访次数')),
                ('lastVisitTime', models.TimeField(verbose_name='上次拜访时间')),
                ('intention', models.TextField(verbose_name='公司意向')),
                ('score', models.IntegerField(verbose_name='公司评分')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactor_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('contactor_gendar', models.CharField(max_length=5, null=True, verbose_name='性别')),
                ('contactor_dialNumber', models.IntegerField(verbose_name='电话号码')),
                ('contactor_email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('project_description', models.TextField(verbose_name='项目内容')),
                ('beginTime', models.DateField(verbose_name='开始时间')),
                ('endTime', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(blank=True, max_length=5, null=True, verbose_name='项目状态')),
                ('contactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Contactor', verbose_name='联系人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='工资')),
                ('bonus', models.IntegerField(verbose_name='奖金')),
                ('reimburse', models.IntegerField(verbose_name='报销额')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('staff_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('staff_gendar', models.CharField(max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('education', models.CharField(blank=True, max_length=10, null=True, verbose_name='学历')),
                ('staff_zone', models.CharField(blank=True, max_length=20, null=True, verbose_name='区域')),
                ('qualification', models.CharField(blank=True, max_length=20, null=True, verbose_name='职称')),
                ('staff_email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='E-mail')),
                ('staff_dialNumber', models.IntegerField(blank=True, null=True, verbose_name='电话号码')),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Authority', verbose_name='权限等级')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Staff', verbose_name='员工'),
        ),
    ]
