# Generated by Django 2.0.1 on 2018-01-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180130_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Staff', verbose_name='员工'),
        ),
    ]
