# Generated by Django 2.0.1 on 2018-01-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180126_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='username',
        ),
    ]
