# Generated by Django 2.0.1 on 2018-02-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_staff_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
        migrations.AddField(
            model_name='staff',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='工资'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='奖金'),
        ),
        migrations.AddField(
            model_name='staff',
            name='reimburse',
            field=models.IntegerField(blank=True, null=True, verbose_name='报销额'),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
