# Generated by Django 2.0.1 on 2018-01-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_project_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Authority', verbose_name='权限等级'),
        ),
    ]
